### ISSUE TITLE
Add an example storybrew project in the main branch.

### ISSUE THREAD

**Issue by KazumaKun1** [Tunnelbliick/maniaModCharts#10]
Hello, 
I have been exploring this library for quite a while now and I was wondering if you can make an example storybrew project for reference?
I would appreciate that if you can add that.

**Comment by Tunnelbliick** [comment]
it's a fair point. There's only reference projects u can look at ATM, tho there's a lot that changed between this and now already.

I'm planning to write everything out in a wiki later on.
But currently i don't have the time for that yet.

https://github.com/Tunnelbliick/picturedAsPerfect

**Comment by Tunnelbliick** [comment]
Just released this

https://github.com/Tunnelbliick/Make-it-Funky

it might be a better project to look over. Since it uses like 1.05 and is generally better set up.

**Comment by Tunnelbliick** [comment]
Full Documentation will follow in the future, since i obtained the notosu.sh domain aswell for this already.
probably under wiki.notosu.sh once i have it setup.

**Comment by KazumaKun1** [comment]
> Just released this
> 
> https://github.com/Tunnelbliick/Make-it-Funky
> 
> it might be a better project to look over. Since it uses like 1.05 and is generally better set up.

sorry for the late reply, 
Thank you so much for this.

**Comment by Tunnelbliick** [comment]
> > Just released this
> > https://github.com/Tunnelbliick/Make-it-Funky
> > it might be a better project to look over. Since it uses like 1.05 and is generally better set up.
> 
> sorry for the late reply, Thank you so much for this.

Im prob releasing 2.0 directly which is basically a recode of a lot of functions just making everything more consistent, aswell as adding resolves for overlapped commands.

Meaning you can just call "rotate, move and scale" all at the same time and it will execute them, just fine.

This additionally will make writing doc alot easier, since i wont have 1000 different functions for a specific thing.

It still neds a bit of optimization but should prob release a build of it tomorrow.

This will unlock new heights.

**Comment by Tunnelbliick** [comment]
v2 is released additionally i generated a doc site with the help of gpt, if a demo project is still wanted please reply to this again, for now im gonna close this issue with the inclusion of a doc page.

Demo projects if big, would probably go out of sync quite fast.

If you use notosu please link back to https://notosu.sh instead of this repository
